# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 341ecbce5e57a0e05b69e94214e31cfc5185daa57f8a61dc4b6cde6da9bd4f868fb6d06f75fe88dda41aea2a8947143dd9c5f0e8a158e0341381728b2a54b89c

test:
  secret_key_base: d41f1e54381cc48311cd53857796a36dc5785548296e682cbfbefae8ca45d9b6ff9a70dad58180e54c8ea061c3d43744463bfde4d691cc7bb6cff5d6b9dcfeea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
